name: Scheduled work Embacy-monitoring
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  get-empty-slots:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Golang
        uses: action/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run app
        run: go run embacy-monitoring
